apiVersion: ENC[AES256_GCM,data:PbQ=,iv:rGINpHtXiZjlhR+FYXax2EU8fzEfgCSNnPOM0lEAyaA=,tag:0VqQS8ohTm3RGk8eaJb04Q==,type:str]
kind: ENC[AES256_GCM,data:cQfjg+ln,iv:7DOmWsCTgLM17wBtpxxnt1TiIba793A6RtVcgR9cu3k=,tag:bv1Nt2FZVWWOiQq0JkBn+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d0KZjCtQ+ksfSB3REM0BKR+du6I=,iv:5/n+RBVcAIcojiPWUNBcU9NC5qtFpobY6sv6//X9z5Y=,tag:LJM7R4xXbDqhcWMUqVf6ow==,type:str]
    namespace: ENC[AES256_GCM,data:DZw+yziSMUrTzA==,iv:gGzfYMjp7KDlunq3RuGFipf6kHlL3jDcsY2a9DSklGc=,tag:+0Jy8HFz2aD2zHgWwAnhzQ==,type:str]
type: ENC[AES256_GCM,data:4Maf4ri1,iv:9rNyIbkdjNyZSkllWmBcYKHegGTL8rViK4pLwQ0KSls=,tag:GvVt1FpthvuvhYj+R3v18g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:bi/S2Nwswec=,iv:QThczl05XBGXRsRgNstw1DWaLNO9AeVN0rJoroHN4Ak=,tag:cNA3jNwQjRv72ZuZhFetZw==,type:str]
    password: ENC[AES256_GCM,data:r2mMldOrjZo3XcjpaQpo,iv:tltY/2NUPgmKn0m3qXt2hZ7JFsufomYvUquAiDhKFqM=,tag:z9pH/agiLWjE7YU4h4bDRQ==,type:str]
sops:
    age:
        - recipient: age1qq0wr9u58s4ftwksfgn08jwkmjasuzx8nrlwa3ha7akv25fd0g9q37l897
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud2RMSGpaNWVhK1MzbXRI
            N0xEZjVKeDlaU3BHMnBFZXF5bXBzOWZOMWlFCkpYUDN0VzYvV3BNbS9wcmkxUklL
            MGI5MUt6cXdTcC9vMGpWNnV1WW1RRlUKLS0tIGFtSnZBckdVMWxnN1FEclBPUG5V
            R09qQVNZS0FCVnliUzhEdThKUzcwaEUKX71ePI3qUrGTr/sWf/hA5GEXQrmYmnNH
            kLd1LsXXGAo25Yw/2zTlrIUaMQZBpGo5LHJefCIZrpM4HRCyr5+sUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T23:33:22Z"
    mac: ENC[AES256_GCM,data:i8l5O0z12N1UkZTk86hM3X9yYESmJMrRQhLwoAsCNvyIn3ouvYma3155we/5EW3Fg1shWNicTCsg9JAy0TCt+PZc8twbmGF7Zx6Orfrvre47477TnWU3p/UMvkzKoLtrGh5Ds4URQHtfnlxV5Rdo0U/wwJAAU0IPiC7Iw+msO44=,iv:TUZham2VO/DTp8fKpVQ6KSfdSWA6BjDkLzHt0w/E0lw=,tag:i0bASq4UpigqzBWxbpNMNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
