---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: local-path-provisioner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    storageClass:
      name: local-path
      defaultClass: true
      reclaimPolicy: Retain
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /opt/local-path-provisioner
