apiVersion: ENC[AES256_GCM,data:Zck=,iv:ZuY+zwLndWWbzPRJpGr61ETrzAE4wczqdyYGE9WPOuk=,tag:dtD2y2rFBJLteYBxx3xqgA==,type:str]
kind: ENC[AES256_GCM,data:xuunU0P/,iv:rZkyTXM6fLvNaB1zpEdtHz45zLFPGCd0UoTq8gfzbNY=,tag:WIKVsUiz7/G8acBrMuFF9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UpiTpFq2oCRwUpW+002zK881,iv:8nRQPPv1F0wBfwA/jl7P+OikN2eCccRvLMD91nr7hgw=,tag:QdTAILVgdmQrdz5VPtI41A==,type:str]
    namespace: ENC[AES256_GCM,data:Oq3/QsLISEE=,iv:IxZZhD6RyCE5wyxa5X5NKVzDxpAgeqBqfcc94vZ3b2M=,tag:OidAcnJmxDkmxHNuGy1mjA==,type:str]
type: ENC[AES256_GCM,data:EGrpdLoe0BYz83DjWMJBXPxRSeZw79sC,iv:KBnHgHbVSQ8X0l0LkvLkzkvlqGZKEU6uL/PJRrWUkss=,tag:fkgfxqjCe3SyZVE8APl7Hg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Kjs1,iv:J1Vui60KKlQUtaXlrbQIQNGwLfzJcUiOj4dDyvjHpDk=,tag:8N4nSIWZZHPOCd+dbbNXGw==,type:str]
    password: ENC[AES256_GCM,data:18grmxPUGY0=,iv:tQLVDHpsZ59AN1l1xScNQwHCgJAOkibxNDIckWU8RSA=,tag:XwpIkdyGjyRykjsjEtDf5w==,type:str]
sops:
    age:
        - recipient: age1qq0wr9u58s4ftwksfgn08jwkmjasuzx8nrlwa3ha7akv25fd0g9q37l897
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Sldxc1VReGg0T0JPS1ps
            bkVKanc4Y1Jtblc5a2J5Zm1KT0dGSHpPVTJFCmxqTjNZaWtZUjBnc2JOdmVUcFFw
            TnZtWXkvcThnYTdGbEx5SFMzOU5jTTAKLS0tIFM3YitNSzU5blRXVlRmRGIrSnBy
            UmpISnVxTGVqQzU1Qms5WVZwOWs1bVUK40zvYQYGavAwK7WDXzkweQI/nq3fh5Rl
            s13gSGM5FRfUzzjdtniwlV2uQUmWJMCey00UIQuaSnPR7acafU12jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:22:40Z"
    mac: ENC[AES256_GCM,data:DpIjLQkFYIkIOMtsRAF5N6nuQifD94DcJTAydFfUInYQsq52ikj+V9k6hcuIFjVqe1UE0ttN9nfIjBcJMY1/LMAUBwIfae4AwzwPLJv4mP/oVRYq+x2DyxL2fZA2awI0xCM2hDB/lW60ca0GmY7YfEGgM6RbKdbJpEP2FSzuXpk=,iv:BMH1wtlS6BPIhAc+lm8BTBLPeYh47nCVN8Q9TXXhsFc=,tag:tMfPP2nJjelZCPvJ8GWiDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
