apiVersion: ENC[AES256_GCM,data:oaU=,iv:p0m4tx6VUMVVAbLoKh6MqzEySQeF6J5JVN62oCb5N1o=,tag:XO4kmtJ3c3L/urV3X6E4kg==,type:str]
kind: ENC[AES256_GCM,data:2u8qAGIe,iv:6BNdiyxO8Xvg3vSSuVTRsTIRGzMMVflIvlLTCLTRAeQ=,tag:s/nUC6xaIDUYQyS5N2Q88A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7l0xFjl0Gmc+11pk9v5dYw==,iv:oOOZHNJnBp0Ca1bWCxqbkFx5ZaLvgyT3GPXC+ogW48w=,tag:GtCL18NJrwl3fRwXt0o5Lw==,type:str]
    namespace: ENC[AES256_GCM,data:XOw2EHi08+XyoQ==,iv:RqTticrG28bq/B8QWShZefBDgWgimnEfl6AkdcJ330M=,tag:ew8XhCZ4kALGGfG/7P8x2Q==,type:str]
type: ENC[AES256_GCM,data:esjZ9uje,iv:bCAawHoguV9oKUBYpGaRgW7dtR+99oYn6dICINbJjKs=,tag:M+bJoAcE5dT6+b7i0MFv2g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:xjp31lkcgQ==,iv:fMkZrDCrKcmIGnlhEwmMHfLZQub75hMPNm5ex/xdG5w=,tag:GRM/+nKgSHTzGezEBPy3Vw==,type:str]
    password: ENC[AES256_GCM,data:GNlZlwYBZ/Mup0zOTg==,iv:E8B2m+H37midtQl7FKfu1dbbPIevt31T/sZhiut4ooo=,tag:+tRnJdnVsi4qY0h77DIdxw==,type:str]
sops:
    age:
        - recipient: age1qq0wr9u58s4ftwksfgn08jwkmjasuzx8nrlwa3ha7akv25fd0g9q37l897
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYXRaRkNHUHVZMzdZbTRG
            cjFWQ3J4R1praHlxd0dCZzdMRGk5RHc4bmtnCnN0VmV1em8rMnRLZlcwRnJXL3Fk
            amU4WHVhNEQyalhvKy9jUUxFR29RMEEKLS0tIEt6c29URXJYT3RwRVFvZ3duaU5T
            RjZNYXFzKzJ0YUV0dDlLbUNCVVd4aDAKNphm0KYMvRrToExrO4qe0B4XNnEe8YFq
            H6UZaLYXv2Bkwn36i0w4jCpLUtDLOGHLvNW6taEEpDseGunEb/XDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:22:40Z"
    mac: ENC[AES256_GCM,data:9r0w4qZU23l443Oi20SpcmP0VLuW/Scl/19dcVDOThvnQK1F9uThcyaCU5r3VyF/JZCV/5EFDC7poAN8ICxiOVXFTBSpXmUkGHDWOWt5DeliDTYSSD6X/bEXEbNZpsFQesba+8bklmpBw9WbGYJyupsd/yC7rlJ0PBRnqNLjtvM=,iv:UvvN3rBZyV9j/8hd0/fLvczNQp7TYXiEBN8hbbL/iDA=,tag:ji/avW+E0YddH0Gn1n8Xdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
