apiVersion: ENC[AES256_GCM,data:eGk=,iv:2Ov+seYt9HRmZ5FfDg8xYBecLfL1j0xo3e8jddDIrPs=,tag:KWnQOEzkygS/B8qciVIujw==,type:str]
kind: ENC[AES256_GCM,data:ah65KmQq,iv:2ix7vHQZSKK3d3+kHMe+nhKCQCqIk7qqXnYkzyO+W2o=,tag:zuINSEz36L4/e8MAzsUD0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Cql4KExuuLbVkJk5PfQUFU7Zr4RCvYCQow==,iv:u83JFCMcNvhXd2PxKZUVGAsojpFaVGyvtywk7oE5RDc=,tag:Rgje8DdmoSTsErMuKexyVw==,type:str]
    namespace: ENC[AES256_GCM,data:lwNUULxF+HEmCw==,iv:49Hw64rNVP3SE20wQN97NnU24U4KNaBXKrFOYNhVO98=,tag:HIHTGw1UBzjX2oISO4FalA==,type:str]
type: ENC[AES256_GCM,data:r8EN4XyZ,iv:rFw3sdq9jPz1MUz56tADo7I0cCOesQ8timMAJNms9fY=,tag:O8ebTgm6ccYiJczgS/xgIw==,type:str]
stringData:
    prometheus-username: ENC[AES256_GCM,data:ISLc4F7uDg==,iv:sq9uArKGLn7KnTuvzyJFlfx5uS7fL3LwqgiOGhsnWWM=,tag:332o9iLop1BzMT+ckWYpXA==,type:str]
    prometheus-password: ENC[AES256_GCM,data:xlPslMiaUEKDhXvPJ6FqrbFxcEcdzLx+IlKB6t6nL5po/OUSTChJW/tXme6bVy955u6SLjxgj9mi6PxdTXdPm9hp0B2ZhwFHQx8eJbO1ahoCo3EyT3IwVrrHioL1W7aA6aaoIunAHV9azB3f/Y0eHKkVjVNzw0dl6pDsFJ2/33OL1h3EvEEEJmN+rm1DJq5byB3snVBknxMpdYdWmFL5OQ==,iv:f+s5MFRaMGy0wW8GJkZg0lauxIwdKME3rLmqEeKSSGk=,tag:oF6pF935NM+q/AOH5PowtQ==,type:str]
    loki-username: ENC[AES256_GCM,data:EvdsCxBWiw==,iv:U8LJQzDEvzwH7Z0IacGHH/NvkHQG+RZ9xG6cm6IuZCc=,tag:qI1JvEKUrsX9D1HZHcOJ9Q==,type:str]
    loki-password: ENC[AES256_GCM,data:ZmUlQ17tS0v8JvatTir7QPtNYTSNNlPQTgn3pE+8n93CRHKtTU96x3S4lYCLknuJk2pWJJZ7tQikuYoNQb2eViFfQCkhXNcfYqyZ1pqFfUKpRpJDDWow/PzgltuOhEV9UuzQ2p3WgFNcvpNpbR0FsM1oIkgvokCMT4aqKA3QBPQ7NthHz3WwsU/KW5ztcADC9b2D6qcVSKHGSPak3pj1Bw==,iv:uQoRPMrY+dA3l8V/GvhU40h0MH6vhUEzR/qv6HzlgDI=,tag:i4vYK4J+CyMoeq2VDnET8g==,type:str]
    otlp-username: ENC[AES256_GCM,data:gVfdrYFa8w==,iv:TVchCudn2/147R5LmNNmsuq1IjVJVbF2bDE0OPhdti0=,tag:9FIIhfiEdfwpKbtUWCwtXA==,type:str]
    otlp-password: ENC[AES256_GCM,data:ogFc7dhJoao6zb4xgOLLb6yeUMzIsqBLpXTmytF94M1lzhC1eWQWZqrgq6JBPW1T6kIEKwQOcHstpyIDKIiG73x0v3PC8I7j057/RmrDZLIWfnotwkJSj7umo87eRRQmMzweGKyYX123e4nSdTu35Kx69tQE0tUEdRbOjB4P9b2Hue+4s62QDbWh+RGaHuElAp8jYF4vOW5XziQmNDq8sA==,iv:ZRUf2Ntc/4dQvCDYcH7Od09gYdzDZqNbfxBE1sO3w38=,tag:kZHTDmwBU8LzfFh2tZxzyg==,type:str]
sops:
    age:
        - recipient: age1qq0wr9u58s4ftwksfgn08jwkmjasuzx8nrlwa3ha7akv25fd0g9q37l897
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGT01QS1c3bWt5d3RRYVdR
            YTZ2KzR1NTFXNy8wamhDTGVKaUdlaGlOc0ZZCjc5N2Y3SmVoNmZpcG55aWNDSnRS
            R2ZDRVBsSDdacjgvN25YQk96MmgzTjQKLS0tIHNLYzJwd0lrdUdaeklCdGNPM0w3
            RTdhdk54ak9aMmxnU3Fpd2QwUlBZalkKErdukdjTcO0d6x6GjqKgQtU4Ud+ljOei
            sI2X+Ezsa0UxKd5eZhboZIGAnU1vuh8btVqe9zyrhhLuNox97yyU+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:22:39Z"
    mac: ENC[AES256_GCM,data:dvqvRCs1/hA96hw/th2dTWdt9HczTJlPimKEYr0aUa6KO8nSQmHFOlIuT5MDxedYn5Xp1uO16RY34nP1JDzNFvgpoBGDU0gaO7kYLpj3vPRPTH05F+55TvcSoiKb+AklyiJIPn6FYpISMRuPOMpskky+M4PbmEC0tvfuLw5I7cg=,iv:cwF1WiEn+I+da2N5xpgmbjqpVJBERHHUADVoxWY3dHc=,tag:mwWZgPqzVb8U5ZH8hMMJKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
